select * from action;

CREATE TABLE ACTION (
ACTIONID SERIAL,
ITEMID TEXT NOT NULL,
ACTION_TYPE TEXT NOT NULL,
ITEM_DESCRIPTION TEXT DEFAULT NULL,
PRICE NUMERIC (5,2),
ACTION_TS TIMESTAMPTZ NULL DEFAULT current_timestamp
);
